apiVersion: v1
appVersion: "6.1.0"
description: A Sample PingAccess Helm chart
name: pingaccess
# v0.0.4 - Moved Service Variables to Global (for C360 Chart)
# v0.0.5 - Added ACME port on Deployment and Service yamls
version: 0.0.5
home: https://www.pingidentity.com/
sources:
- https://github.com/patrickcping/pingidentity-helm-charts
- https://github.com/pingidentity/pingidentity-docker-builds
- https://github.com/pingidentity/pingidentity-server-profiles
