# Default values for pingaccess.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pingidentity
  name: pingaccess
  tag: 2006-6.1.0
  pullPolicy: IfNotPresent
  readinessCommand: /opt/liveness.sh
  livenessCommand: /opt/liveness.sh

pingaccess:
  logging: INFO
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git 
    SERVER_PROFILE_PATH: getting-started/pingaccess
    SERVER_PROFILE_BRANCH: master

license:
  acceptEULA: false-pa-values
  licenseSecretName: pingaccess-license
  # Using the devops key is best suited to development or sandbox environments.  In other cases create a license secret
  useDevOpsKey: false
  devOpsKey:
    user: 
    key: 

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  admin:
    port: 9000
    name: pa-admin
  runtime:
    port: 3000
    name: pa-runtime

ingress:
  enabled: false
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   kubernetes.io/ingress.class: "nginx-public"

  # hosts:
  #   - host: my.host.pingaccess.host.com
  #     paths:
  #     - path: /
  #       backend:
  #         servicePort: 3000
  #   - host: my.host.admin.pingaccess.host.com
  #     paths:
  #     - path: /
  #       backend:
  #         servicePort: 9000

  # The following section adds TLS specific configuration for the ingress descriptor.  Example:
  # tls:
  #   - secretName: tls-secret-admin
  #     hosts:
  #       - my.host.admin.pingaccess.host.com
  #   - secretName: tls-secret
  #     hosts:
  #       - my.host.pingaccess.host.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1
  #   memory: 1.5Gi
  # requests:
  #   cpu: 1
  #   memory: 1.5Gi

nodeSelector: {}

tolerations: []

affinity: {}
