{{if .Values.global.license.useDevOpsKey -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pingfederate.name" . }}
    helm.sh/chart: {{ include "pingfederate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "pingfederate.fullname" . }}-devops-secret
type: Opaque
stringData:
  PING_IDENTITY_DEVOPS_USER: {{ .Values.global.license.devOpsKey.user }}
  PING_IDENTITY_DEVOPS_KEY: {{ .Values.global.license.devOpsKey.key }}
{{ end -}}