apiVersion: v1
appVersion: "1.4"
description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
name: pingcentral
# v0.0.2 - Injecting Global Envs into config-map
# v0.0.3 - Map the license decision to global
# v0.0.4 - Map the license decision to global in secrets.yaml
# v0.0.5 - Tripping version number
# v0.0.6 - Adding PC_ADMIN_MODE mapping in configMap
# v0.0.7 - Adding `progressDeadlineSeconds` to deployment
# v0.0.8 - Trying to get PC to pause properly - moved `progressDeadlineSeconds` under spec.containers.
# v0.0.9 - Trying `wait-for` injection
# v0.0.10 - Learning yaml...
# v0.0.11 - Extendeding `liveness` initialDelaySeconds
# v0.0.12 - Removing pause for PF - not needed with Compass SSO
# v0.0.13 - Adding swap of PC_ADMIN_MODE to `true` or `false`
# v0.0.14 - Convert `PC_ADMIN_MODE` properly for PING_CENTRAL_OIDC_ENABLED
version: 0.0.14
home: https://www.pingidentity.com/
sources:
- https://github.com/cprice-ping/pingidentity-helm-charts
- https://github.com/pingidentity/pingidentity-docker-builds
- https://github.com/pingidentity/pingidentity-server-profiles
dependencies:
- name: mysql
  version: ^6.14.4
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enabled