apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postman-configmap
data:
  postman_vars.json: |
    {
        "id": "40199d03-d15c-47e4-b502-8b62f98479d1",
        "name": "Solution-Customer360",
        "values": [
            {
                "key": "pfAdminURL",
                "value": "https://{{ .Release.Name }}-pingfederate",
                "enabled": true
            },
            {
                "key": "pfBaseURL",
                "value": "https://{{ .Values.global.VIRTUAL_HOSTNAME }}",
                "enabled": true
            },
            {
                "key": "pingIdSdk",
                "value": {{ .Values.pingidsdk | quote }},
                "enabled": true
            },
            {
                "key": "sdkAppId",
                "value": {{ .Values.global.PINGIDSDK_APPID | quote }},
                "enabled": true
            },
            {
                "key": "paAdminURL",
                "value": "https://{{ .Release.Name }}-pingaccess:9000",
                "enabled": true
            },
            {
                "key": "paVirtualHost",
                "value": {{ .Values.global.VIRTUAL_HOSTNAME | quote }},
                "enabled": true
            },
            {
                "key": "pdsAdminURL",
                "value": "https://{{ .Release.Name }}-pingdatasync",
                "enabled": true
            }
        ],
        "_postman_variable_scope": "environment"
    }