apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "customer360.name" . }}
    helm.sh/chart: {{ include "customer360.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-env-vars
data:
  ADMIN_CLIENT_ID: {{ .Values.global.envs.oidcClientId | quote }}
  ADMIN_CLIENT_SECRET: {{ .Values.global.envs.oidcClientSecret | quote }}
  ADMIN_CLIENT_ISSUER: {{ .Values.global.envs.oidcIssuer | quote }}
  ADMIN_CLIENT_AUTHZ: "{{ .Values.global.envs.oidcIssuer }}/authorize"
  ADMIN_CLIENT_TOKEN: "{{ .Values.global.envs.oidcIssuer }}/token"
  ADMIN_CLIENT_USERINFO: "{{ .Values.global.envs.oidcIssuer }}/userinfo"
  ADMIN_CLIENT_LOGOFF: "{{ .Values.global.envs.oidcIssuer }}/signoff"
  PF_ADMIN_PORT: {{ .Values.pingfederate.service.admin.port | quote }}
  PF_ADMIN_HOSTNAME: "pingfederate-{{ .Release.Name }}.ping-devops.com"
  PF_ADMIN_TITLE: {{ .Release.Name }}
  PF_BASE_URL: {{ .Values.global.clientConnection.externalHostname | quote }}
  {{- if .Values.global.useCases.delegatedAdministration.enabled }}
  PD_DELEGATOR_PUBLIC_HOSTNAME: {{ .Values.global.clientConnection.externalHostname | quote }}
  PF_ENGINE_PUBLIC_HOSTNAME: {{ .Values.global.clientConnection.externalHostname | quote }}
  PF_ENGINE_PUBLIC_PORT: "443"
  PF_DELEGATOR_CLIENTID: "Delegator"
  PD_ENGINE_PUBLIC_HOSTNAME: {{ .Values.global.clientConnection.externalHostname | quote }}
  PD_ENGINE_PUBLIC_PORT: "443"
  {{- end }}