apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-vars
data:
  ADMIN_CLIENT_AUTHZ: "{{ .Values.global.oidcIssuer }}/as/authorize"
  ADMIN_CLIENT_TOKEN: "{{ .Values.global.oidcIssuer }}/as/token"
  ADMIN_CLIENT_USERINFO: "{{ .Values.global.oidcIssuer }}/as/userinfo"
  ADMIN_CLIENT_LOGOFF: "{{ .Values.global.oidcIssuer }}/as/signoff"