apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public-passthrough
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: {{ .Release.Namespace }}-consoles-ingress
spec:
  # Use the AWS Route53 FQDNs to access the Admin Consoles
  rules:
  # This rule gives external access to the PingAccess Admin Console
  - host: pingaccess-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
           serviceName: {{ .Release.Name }}-pingaccess
           servicePort: 9000
  # This rule gives external access to the PingFederate Admin Console
  - host: pingfederate-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: {{ .Release.Name }}-pingfederate
          servicePort: 443
  # This rule gives external access to the PingData Admin Console
  - host: pingdataconsole-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: {{ .Release.Name }}-pingdataconsole
          servicePort: 8443
  # This rule gives external access to the PingDataGovernance-PAP Admin Console
  - host: pingdatagov-pap-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: pingdatagov-pap
          servicePort: 443
  # This rule gives external access to the PingCentral Admin Console
  - host: pingcentral-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: {{ .Release.Name }}-pingcentral
          servicePort: 9022
  # This rule gives external access to the PingDirectory ConfigAPI
  - host: pingdirectory-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: pingdirectory
          servicePort: 443
  # This rule gives external access to the PingDataGov ConfigAPI
  - host: pingdatagov-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: pingdatagov
          servicePort: 443
  # This rule gives external access to the PingDataGov-PAP Console
  - host: pingdatagov-pap-{{ .Release.Namespace }}.ping-devops.com
    http:
      paths:
       - backend:
          serviceName: pingdatagov-pap
          servicePort: 443