apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "customer360.name" . }}
    helm.sh/chart: {{ include "customer360.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx-public-passthrough
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: {{ .Release.Name }}-client-ingress
spec:
  rules:
  - host: {{ .Values.global.clientConnection.externalHostname }}
    http:
      paths:
      - path: /.well-known/acme-challenge/
        backend:
          serviceName: {{ .Release.Name }}-pingaccess
          servicePort: {{ .Values.pingaccess.service.acme.port }}
      - backend:
          serviceName: {{ .Release.Name }}-pingaccess
          servicePort: {{ .Values.pingaccess.service.runtime.port }}