apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: {{ include "customer360.name" . }}
    helm.sh/chart: {{ include "customer360.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-pingconfig
spec:
  template:
    spec:
      containers:
      - env:
        - name: COLLECTIONS
          # Customer360 --> PA as Ingress (Needed in Kubernetes)
          # value: https://www.getpostman.com/collections/f1f5ffff5ddd891e720d,https://www.getpostman.com/collections/eaa397bd3a35ef3095c1
          value: {{ .Values.pingconfig.collections.value }}
          # value: {{ .Values.useCaseCollections.customer360 }},https://www.getpostman.com/collections/eaa397bd3a35ef3095c1{{ if .Values.global.useCases.consentManagement }},{{ .Values.useCaseCollections.consentManagement }}{{ end }}{{ if .Values.global.useCases.consentEnforcement }},{{ .Values.useCaseCollections.consentEnforcement }}{{ end }}{{ if .Values.global.useCases.delegatedAdministration }},{{ .Values.useCaseCollections.delegatedAdministration }}{{ end }}
        image: pricecs/pingconfigurator:1.1
        imagePullPolicy: "Always"
        name: pingconfig
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/postman_vars.json
          name: {{ .Release.Name }}-postman
          subPath: postman_vars.json
      restartPolicy: Never
      serviceAccountName: ""
      volumes:
      - configMap:
          items:
          - key: postman_vars.json
            path: postman_vars.json
          name: {{ .Release.Name }}-postman
        name: {{ .Release.Name }}-postman
status: {}