apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pingconfig
  name: pingconfig
spec:
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: pingconfig
    spec:
      containers:
      - env:
        - name: COLLECTIONS
          # Customer360 v2.0.0
          #value: https://www.getpostman.com/collections/f1f5ffff5ddd891e720d
          # Customer360 v2.0 --> PA as Proxy
          value: https://www.getpostman.com/collections/f1f5ffff5ddd891e720d,https://www.getpostman.com/collections/eaa397bd3a35ef3095c1
          #Customer360 v1.3.2 --> PA as Proxy ...?
          #value: https://www.getpostman.com/collections/344bbc13f4ccd4ebc5f5,https://www.getpostman.com/collections/eaa397bd3a35ef3095c1,https://www.getpostman.com/collections/4f27daff62383fd3f4ed,https://www.getpostman.com/collections/3db252f80d56599a5f46,https://www.getpostman.com/collections/a1378e567df17ff15f10,https://www.getpostman.com/collections/eb7dc32b6d429fd7bcd2,https://www.getpostman.com/collections/246ba03433c2ffe26de0
          # Fullstack - All latest versions
          #value: https://www.getpostman.com/collections/f1f5ffff5ddd891e720d,https://www.getpostman.com/collections/eaa397bd3a35ef3095c1,https://www.getpostman.com/collections/4f27daff62383fd3f4ed,https://www.getpostman.com/collections/6573a75f6042999e5c9f,https://www.getpostman.com/collections/a1378e567df17ff15f10,https://www.getpostman.com/collections/67c0839677fa2b0fad81,https://www.getpostman.com/collections/246ba03433c2ffe26de0
        image: pricecs/pingconfigurator:1.1
        imagePullPolicy: "Always"
        name: pingconfig
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/postman_vars.json
          name: {{ .Release.Name }}-postman-configmap
          subPath: postman_vars.json
      restartPolicy: Never
      serviceAccountName: ""
      volumes:
      - configMap:
          items:
          - key: postman_vars.json
            path: postman_vars.json
          name: {{ .Release.Name }}-postman-configmap
        name: {{ .Release.Name }}-postman-configmap
status: {}