apiVersion: v2
name: customer360
description: A Helm chart to deploy Ping Customer360 into a Kubernetes cluster

type: application

# This is the chart version. This version number should be incremented each time you make changes
# v 0.1.0 - Initial release to repo
# v 0.1.1 - Adding default PingDataConsole settings (values)
version: 0.1.1

# This is the version number of the application being deployed.
appVersion: 2.0.0

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: pingdirectory
  version: ~0.0.5
  repository: "@pingidentity-solutions"
- name: pingdatasync
  version: ~0.0.1
  repository: "@pingidentity-solutions"
- name: pingfederate
  version: ~0.0.1
  repository: "@pingidentity-solutions"
- name: pingaccess
  version: ~0.0.5
  repository: "@pingidentity-solutions"
- name: pingcentral
  version: ~0.0.7
  repository: "@pingidentity-solutions"
- name: pingdataconsole
  version: ~0.1.0
  repository: "@pingidentity-solutions"
