apiVersion: v2
name: customer360
description: A Helm chart to deploy Ping Customer360 into a Kubernetes cluster

type: application

# This is the chart version. This version number should be incremented each time you make changes
# 0.1.0 - Initial release to repo
# 0.1.1 - Adding default PingDataConsole settings (values)
# 0.1.2 - Testing useCase injections (values / job-pingconfig)
# 0.1.3 - Added Use Case processing (_helpers)
# 0.1.4 - Adding Conditional Delegator (`useCases.delegatedAdministrator.enabled: true`)
# 0.1.5 - Adding Regional PingOne URL config
version: 0.1.5

# This is the version number of the application being deployed.
appVersion: 2.0.0

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: pingdirectory
  version: ~0.0.5
  repository: "@pingidentity-solutions"
- name: pingdatasync
  version: ~0.0.1
  repository: "@pingidentity-solutions"
- name: pingfederate
  version: ~0.0.1
  repository: "@pingidentity-solutions"
- name: pingaccess
  version: ~0.0.5
  repository: "@pingidentity-solutions"
- name: pingcentral
  version: ~0.0.7
  repository: "@pingidentity-solutions"
- name: pingdataconsole
  version: ~0.1.0
  repository: "@pingidentity-solutions"
