# Default values for Customer360.
testing:
  # Using the devops key is best suited to development or sandbox environments.  In other cases create a license secret
  useDevOpsKey: true
  devOpsKey: 
    user: "Your Ping DevOps Username"
    key: "Your Ping DevOps Key"
  acceptEULA: NO
  # Ping Global Values
  PING_IDENTITY_PASSWORD: "Your Global Ping Password"
  # Admin Consoles OIDC -- Configured for Compass
  compassOIDC:
    issuer: "Your Admin SSO Client_Issuer"
    client_id: "Your Admin SSO Client_ID"
    client_secret: "Your Admin SSO Client_Secret"
  # Hosting Environment
  VIRTUAL_HOSTNAME: "Your Virtual Hostname FQDN"
  # PingID SDK App is REQUIRED by Customer360
  PINGIDSDK_APPID: "Your PingID SDK AppID"
  # PD Variables
  USER_BASE_DN: dc=customer360.com
  # Used in the DelAdmin Email template
  PF_BASE_URL: "Your PD BaseURL"

# Product variables
pingdirectory:
  pingdirectory:
    envs:
      SERVER_PROFILE_BRANCH: master
      SERVER_PROFILE_URL: https://github.com/pingidentity/Customer360.git
      SERVER_PROFILE_PATH: pingdirectory
      MAX_HEAP_SIZE: 768m
  logging: INFO
  persistentvolume:
    enabled: false
  license:
    # Used if `useDevOpsKey` set to false
    licenseSecretName: pingdirectory-license

pingfederate:
  pingfederate:
    envs:
      SERVER_PROFILE_BRANCH: master
      SERVER_PROFILE_URL: https://github.com/pingidentity/Customer360.git
      SERVER_PROFILE_PATH: pingfederate
      # PingFed Chart uses a PARENT - these lines remove it
      SERVER_PROFILE_PARENT: ""
      # Used for the OIDC SSO - `redirect_uri` will be set to https://PF_ADMIN_HOSTNAME:PF_ADMIN_PORT
      PF_ADMIN_MODE: "LDAP"
  logging: INFO
  persistentvolume:
    enabled: false
  license:
    # Used if `useDevOpsKey` set to false
    licenseSecretName: pingfederate-license
  service:
    type: ClusterIP
    admin:
      port: 9999
      name: pf-admin
    engine:
      port: 9031
      name: pf-engine 

pingaccess:
  pingaccess:
    logging: INFO
    envs:
      SERVER_PROFILE_URL: https://github.com/pingidentity/Customer360.git 
      SERVER_PROFILE_PATH: pingaccess
      SERVER_PROFILE_BRANCH: master
  license:
    licenseSecretName: pingaccess-license 

# PingCentral -- configures OIDC logon automatically
# PING_CENTRAL_LOG_LEVEL: DEBUG