apiVersion: v1
kind: Service
metadata:
  name: {{ include "pingdirectory.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pingdirectory.name" . }}
    helm.sh/chart: {{ include "pingdirectory.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
      protocol: TCP
      name: {{ .Values.service.https.name }}
    - port: {{ .Values.service.ldaps.port }}
      targetPort: {{ .Values.service.ldaps.port }}
      protocol: TCP
      name: {{ .Values.service.ldaps.name }}
    - port: {{ .Values.service.ldap.port }}
      targetPort: {{ .Values.service.ldap.port }}
      protocol: TCP
      name: {{ .Values.service.ldap.name }}
    {{- if .Values.service.apis.port }}
    - port: {{ .Values.service.apis.port }}
      targetPort: {{ .Values.service.apis.port }}
      protocol: TCP
      name: {{ .Values.service.apis.name }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "pingdirectory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}